#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Proc-ProcessTable
Version  : 0.55
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/J/JW/JWB/Proc-ProcessTable-0.55.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/J/JW/JWB/Proc-ProcessTable-0.55.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libproc-processtable-perl/libproc-processtable-perl_0.55-1.debian.tar.xz
Summary  : 'Perl extension to access the unix process table'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Proc-ProcessTable-lib
Requires: perl-Proc-ProcessTable-man

%description
Proc::ProcessTable
Please use rt.cpan.org to submit bugs and patches.
MAINTENANCE STATUS
==================
This module is now being lightly "maintained" by Jonathan Swartz <swartz@pobox.com>.  I
have nearly zero knowledge of the implementation within but wanted to rescue the
distribution from abandonment and try to get critical bug fixes out. This will need to be
a community effort.

%package lib
Summary: lib components for the perl-Proc-ProcessTable package.
Group: Libraries

%description lib
lib components for the perl-Proc-ProcessTable package.


%package man
Summary: man components for the perl-Proc-ProcessTable package.
Group: Default

%description man
man components for the perl-Proc-ProcessTable package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Proc-ProcessTable-0.55
mkdir -p %{_topdir}/BUILD/Proc-ProcessTable-0.55/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Proc-ProcessTable-0.55/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Proc/Killall.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Proc/Killfam.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Proc/ProcessTable.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Proc/ProcessTable/Process.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Proc/example.pl
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Proc/ProcessTable/Process/autosplit.ix

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Proc/ProcessTable/ProcessTable.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Proc::Killall.3
/usr/share/man/man3/Proc::Killfam.3
/usr/share/man/man3/Proc::ProcessTable.3
/usr/share/man/man3/Proc::ProcessTable::Process.3
